### ISSUE TITLE
com.android etc not accepted by Google Play

### ISSUE THREAD

**Issue by snomos** [divvun/kbdgen-archived#10]
I have built a release apk, with signatures and everything. Then I have logged in to Google Play to upload the apk (https://play.google.com/apps/publish/).

After upload, I get the following message:

Opplasting mislyktes
- Du lastet opp en APK-fil med en ugyldig versjonskode. Koden må angis og skal være et positivt heltall.
- Du må bruke et annet pakkenavn fordi «com.android» ikke er tillatt.
- Du må bruke et annet pakkenavn, fordi com.android.inputmethod.latin brukes av en forhåndsinstallert app. Ta kontakt med utviklerstøtten for Google Play for å laste opp en forhåndsinstallert app. Finn ut mer..

I recon these are all things that must be fixed by @bbqsrc :smile:

**Comment by bbqsrc** [comment]
The `version` and `build` properties now apply as they should have, as does `packageId`.
