### ISSUE TITLE
\u{0} doesn't create empty key, subsequent keys are left-shifted

### ISSUE THREAD

**Issue by snomos** [divvun/kbdgen-archived#22]
This happens with the macOS generator (haven't tested the other ones yet).

Compare the follwing definition  (from [sma_NO-macos.yaml](https://gtsvn.uit.no/langtech/trunk/keyboards/sma/sma_NO-macos.yaml?p=152753)) with the screenshot:

```
  iso-alt+shift: |
    Ÿ ¡    ®    ¥  ¢ ‰ ¶ \ { } ≠    ¿ \u{0}
    Q ˝    É \u{0} ‡ ˜ Ü ˆ Œ ∏ ˚    ^
    ◊ ∑    ∆    ∫  ¯ ˘ ¬ º ﬂ Ø Ä \u{0}
    ≥ ⁄ \u{0}   Ç  « » “ ” „ · —
```

![skjermbilde 2017-05-16 kl 15 30 10](https://cloud.githubusercontent.com/assets/1255285/26108978/582b85a8-3a4e-11e7-83b3-53b94e675c15.png)

Notice how there is no empty key after **É**, and that the capital **Q** is at the end of the **E** row instead of at the beginning of the **D** row. For each additional zero char, the remaining keys are left-shifted correspondingly.

**Comment by bbqsrc** [comment]
Fixed.
