### ISSUE TITLE
Keyboard bundle doesn't work properly on pre-10.12

### ISSUE THREAD

**Issue by snomos** [divvun/kbdgen-archived#23]
I installed the SMA on a 10.11 system, and while the bundle was properly installed in the correct folder, the keyboard refused to become available and usable in System preferences.

I then copied out one keylayout file + icns file to that same dir (`/Library/Keyboard Layouts/`), and reopened System preferences. Now both the keyboard that I copied out and one other keyboard was accessible. The two windows keyboards still did not show up.

Screenshots:

Working file structure:
![skjermbilde 2017-05-16 kl 15 07 53](https://cloud.githubusercontent.com/assets/1255285/26110523/e9d9e022-3a52-11e7-94f8-43da00b211b4.png)

Both Norway and Sweden versions available, despite only NO installed directly:
![skjermbilde 2017-05-16 kl 15 11 26](https://cloud.githubusercontent.com/assets/1255285/26110603/20626e52-3a53-11e7-9b71-38ddcb9c1c74.png)

But there are more layout resources available in the bundle:
![skjermbilde 2017-05-16 kl 15 11 34](https://cloud.githubusercontent.com/assets/1255285/26110667/4cf37e98-3a53-11e7-813c-be39cc157c93.png)

**Comment by snomos** [comment]
I assume bundles should work, so there must be something else going on. Anyway, [this StackExchange reply](https://superuser.com/questions/665494/how-to-make-a-custom-keyboard-layout-in-os-x) also hints at the possibility of having long-press keys a la iOS. Would that be much work to add?

**Comment by bbqsrc** [comment]
You have to reboot at least once before reporting any bug relating to the detection of a keyboard either as a keylayout file or as part of a bundle prior to it being acceptable as a bug, as macOS is sometimes pedantic about when it will refresh the list.

It is obvious however that the bundle is being loaded, as you show both NO and SE keyboards being generated. The "Windows" layouts may not be showing for any number of reasons, most of them being that the definition used to generate the macOS layout has something missing that makes the operating system ignore it that we haven't caught yet (most likely a missing osx-* layer).

**Comment by bbqsrc** [comment]
A series of bug fixes later, this seems to be working. For me in macOS 10.12, the Windows keyboards are now working, however they are showing up under "Others" and not "South Sami" as one might expect. This might just be because macOS hates me today.

Delete any installed sma keylayouts and bundles, generate from the current kbdgen, install, reboot. Tell me how it goes.
