### ISSUE TITLE
CFBundleVersion is an unchanged 1 for macOS keyboard

### ISSUE THREAD

**Issue by snomos** [divvun/kbdgen-archived#28]
But should be incremented for every build (or somesuch). Cf:

```
$ /usr/libexec/Plistbuddy -c "Print " keyboards/sme/macos/no.uit.giella.keyboardlayout.sme.bundle/Contents/Info.plist 
Dict {
    CFBundleShortVersionString = 1.0.1
    CFBundleIdentifier = no.uit.giella.keyboardlayout.sme
    KLInfo_smeFImac = Dict {
        TISInputSourceID = no.uit.giella.keyboardlayout.sme.smeFImac
        TISIntendedLanguage = se
    }
    CFBundleName = North Sami Keyboard
    KLInfo_smeNOmac = Dict {
        TISInputSourceID = no.uit.giella.keyboardlayout.sme.smeNOmac
        TISIntendedLanguage = se
    }
    CFBundleVersion = 1
    KLInfo_smeSEmac = Dict {
        TISInputSourceID = no.uit.giella.keyboardlayout.sme.smeSEmac
        TISIntendedLanguage = se
    }
}
```

Expected value: something bigger than `1`.

Cf also [this page](http://hboon.com/difference-between-cfbundleversion-and-cfbundleshortversionstring/) (this link is only a reference for the OP).

**Comment by bbqsrc** [comment]
Under the `osx` target provide a `build` property and it will work. It currently defaults to `1`.

Fun bit of trivia: if you don't provide a `version` property, it will autofill to `0.0.0`. 

For bundles, these two fields do not seem to have any practical effect.
