### ISSUE TITLE
Full access toggle is not keyboard specific, triggers crash

### ISSUE THREAD

**Issue by snomos** [divvun/kbdgen-archived#7]
@bbqsrc: To get key clicks when you type, you have to enable full access for your keyboard. The switch applies to all keyboards within one package, and when toggled, enabling key clicks in the keyboard options, it causes the keyboard to crash.

Steps to repeat:
1. compile a release version:
- check out svn `https://victorio.uit.no/langtech/trunk/keyboards/sme`
- `./autogen.sh && ./configure`
- `cd mobile`
- `make`
- `open build/ios/no.divvun.keyboards.sme/TastyImitationKeyboard.xcodeproj`
1. run on a tethered iOS device (tether you iOS device and run (Cmd-R)) (_this should be step two, but the markdown parser either restarts at one, or makes it a sub-level list_ :unamused: )
2. enable the installed keyboards
3. open a suitable app, e.g. Calendar & click on the + sign to get a new entry w/ text fields
4. try turning on the key clicks, notice the message that you have to turn on universal access
5. switch back to the settings app
6. go to e.g. the finnish keyboard, and enable universal access
7. go to the north sami keyboard setting, and notice how universal access has been enabled by the action in step 7.
8. switch to the Calendar app, and try to enable key clicks (possibly disable and then enable again)

The first time I did this, the keyboards crashed and I had to remove and reinstall them. After reinstallation, I am not able to repeat the crash :/.

Anyway, I think it makes sense to let each keyboard have its own setting.

**Comment by bbqsrc** [comment]
Can't reproduce this; it was likely an issue with upgrading uncleanly due to the rather major changes made to the package.

The full access setting is part of the hosting app, not a per-keyboard setting.
